// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppHero: typeof import('./src/components/AppHero.vue')['default']
    AppMenu: typeof import('./src/components/AppMenu.vue')['default']
    AppMenuLink: typeof import('./src/components/AppMenuLink.vue')['default']
    AppSvg: typeof import('./src/components/AppSvg.vue')['default']
    CartActions: typeof import('./src/components/cart-actions.vue')['default']
    CartAddItem: typeof import('./src/components/cart/add-item.vue')['default']
    CartDeleteItem: typeof import('./src/components/cart/delete-item.vue')['default']
    CartItem: typeof import('./src/components/cart-item.vue')['default']
    CartUpdateItem: typeof import('./src/components/cart/update-item.vue')['default']
    CurrentBreakpoint: typeof import('./src/components/current-breakpoint.vue')['default']
    FooterBackToTop: typeof import('./src/components/footer/backToTop.vue')['default']
    FooterPageBanner: typeof import('./src/components/footer/PageBanner.vue')['default']
    HeaderAppMenuTrigger: typeof import('./src/components/header/AppMenuTrigger.vue')['default']
    LazyBackground: typeof import('./src/components/lazy/background.vue')['default']
    LazyImage: typeof import('./src/components/lazy/image.vue')['default']
    LazyLozadBackground: typeof import('./src/components/lazy/lozad/background.vue')['default']
    LazyLozadImage: typeof import('./src/components/lazy/lozad/image.vue')['default']
    MainNav: typeof import('./src/components/MainNav.vue')['default']
    PagesNewsList: typeof import('./src/components/pages/NewsList.vue')['default']
    PagesNewsTab: typeof import('./src/components/pages/NewsTab.vue')['default']
    PagesPageAccordion: typeof import('./src/components/pages/PageAccordion.vue')['default']
    PagesPageBreadcrumbs: typeof import('./src/components/pages/PageBreadcrumbs.vue')['default']
    PagesPageCarousel: typeof import('./src/components/pages/PageCarousel.vue')['default']
    PagesPageCarouselItem: typeof import('./src/components/pages/PageCarouselItem.vue')['default']
    PagesPageHeroInner: typeof import('./src/components/pages/PageHeroInner.vue')['default']
    PagesPageModal: typeof import('./src/components/pages/PageModal.vue')['default']
    PostItem: typeof import('./src/components/post-item.vue')['default']
    ProductItem: typeof import('./src/components/product-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}

export {}
