/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/Author': RouteRecordInfo<'/Author', '/Author', Record<never, never>, Record<never, never>>,
    '/Faq': RouteRecordInfo<'/Faq', '/Faq', Record<never, never>, Record<never, never>>,
    '/Form': RouteRecordInfo<'/Form', '/Form', Record<never, never>, Record<never, never>>,
    '/Inquiry-norml': RouteRecordInfo<'/Inquiry-norml', '/Inquiry-norml', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/ProductionNote': RouteRecordInfo<'/ProductionNote', '/ProductionNote', Record<never, never>, Record<never, never>>,
    '/TopNews': RouteRecordInfo<'/TopNews', '/TopNews', Record<never, never>, Record<never, never>>,
  }
}
